<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6622" started-at="2015-11-29T01:48:57Z" finished-at="2015-11-29T01:49:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6622" started-at="2015-11-29T01:48:57Z" finished-at="2015-11-29T01:49:03Z">
      <class name="allSocialShare.DynamicTestResultsName">
        <test-method status="PASS" signature="start()[pri:0, instance:allSocialShare.DynamicTestResultsName@1d384ee]" name="start" is-config="true" duration-ms="6599" started-at="2015-11-28T19:48:57Z" finished-at="2015-11-28T19:49:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="tD(org.testng.ITestResult)[pri:0, instance:allSocialShare.DynamicTestResultsName@1d384ee]" name="tD" duration-ms="2" started-at="2015-11-28T19:49:03Z" finished-at="2015-11-28T19:49:03Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 0 parameters but the method allSocialShare.DynamicTestResultsName#tD takes 1 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method allSocialShare.DynamicTestResultsName#tD takes 1 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tD -->
      </class> <!-- allSocialShare.DynamicTestResultsName -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
